import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [characters, setCharacters] = useState([]);

  useEffect(() => {
    fetch("https://last-airbender-api.herokuapp.com/api/v1/characters/avatar")
      .then((res) => res.json())
      .then(setCharacters);
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className={styles.title}>Avatar List</h1>

      {characters.length === 0 && <LoadingSkeleton />}

      <ul className="list">
        {characters.map(({ _id, name }) => (
          <li key={_id}>
            <Link href={`/characters/${name}`}>{name}</Link>
          </li>
        ))}

        <style jsx>{`
          .list {
            list-style-type: none;
            display: flex;
            flex-direction: column;
            gap: 1rem;
            padding: 0px;
            text-align: center;
          }
        `}</style>
      </ul>
    </>
  );
}

function LoadingSkeleton() {
  return (
    <div className="container">
      {new Array(5).fill(null).map(() => (
        <div
          style={{
            backgroundColor: "#222",
            width: "14rem",
            height: "1.4rem",
            borderRadius: "9999px",
          }}
          className="pulse"
        />
      ))}
      <style jsx>
        {`
          .container {
            display: flex;
            flex-direction: column;
            gap: 1.25rem;
            margin-top: 2rem;
          }

          .pulse {
            animation: pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite;
          }

          @keyframes pulse {
            0%,
            100% {
              opacity: 1;
            }
            50% {
              opacity: 0.5;
            }
          }
        `}
      </style>
    </div>
  );
}
